npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: https://npm.fontawesome.com/
    npmAuthToken: ${FONTAWESOME_NPM_AUTH_TOKEN}

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.4.1.cjs
