# fly.toml file generated for shy-river-1241 on 2023-03-09T15:34:36-05:00

app = "shy-river-1241"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "ord"
processes = []

[build]
  [build.args]
    NODE_VERSION = "16"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  APP_URL = "https://files.stevenberg.net"
  DB_DATABASE = "/var/www/html/storage/database/database.sqlite"
  LOG_CHANNEL = "stack"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"

[mounts]
    source = "storage_vol"
    destination = "/var/www/html/storage"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
